# Generated by Django 3.2.6 on 2022-06-27 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='county',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='parish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('parish', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.parish')),
            ],
        ),
        migrations.CreateModel(
            name='subcounty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.county')),
            ],
        ),
        migrations.CreateModel(
            name='sub_region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.region')),
            ],
        ),
        migrations.AddField(
            model_name='parish',
            name='subcounty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.subcounty'),
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hckey', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sub_region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.sub_region')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='dictrict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.district'),
        ),
    ]
