# Generated by Django 4.0.4 on 2022-07-18 08:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_county_options_alter_district_options_and_more'),
        ('organisation', '0004_alter_organisation_name_alter_organisation_org_type_and_more'),
        ('person', '0008_person_role'),
        ('lookup', '0009_market_type'),
        ('service_provider', '0005_alter_vehicle_number_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='transporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('date_est', models.DateField()),
                ('gps_lat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('gps_long', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('operation_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.operation_status')),
                ('org', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='person.person')),
                ('village_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.village')),
            ],
        ),
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('date_est', models.DateField()),
                ('gps_lat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('gps_long', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('market_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.market_type')),
                ('operation_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.operation_status')),
                ('org', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation')),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.person')),
                ('village_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.village')),
            ],
        ),
    ]
