from django.contrib import admin
from .models import *

admin.site.register(sex)
admin.site.register(identity_doc_type)
admin.site.register(title)
admin.site.register(tribe)
admin.site.register(nationality)
admin.site.register(education_level)
admin.site.register(next_of_kin_type)
admin.site.register(animal_type)
admin.site.register(breed)
admin.site.register(dominant_color)
admin.site.register(origin)
admin.site.register(status)
admin.site.register(est_type)
admin.site.register(tag_status)
admin.site.register(incident_type)
admin.site.register(incident_level)
admin.site.register(operation_status)
admin.site.register(transfer_status)
admin.site.register(transfer_nature)
admin.site.register(vehicle_make)
admin.site.register(vehicle_model)
admin.site.register(trans_fee_type)
admin.site.register(payment_mode)
admin.site.register(payment_channel)
admin.site.register(quarantine_status)
admin.site.register(quarantine_reason)
admin.site.register(transfer_action_type)
admin.site.register(mode_of_transport)

