# Generated by Django 4.0.4 on 2022-07-17 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_animal_action_type_ownership_change_type_role_and_more'),
        ('person', '0008_person_role'),
        ('organisation', '0003_alter_organisation_org_type_delete_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='lookup.org_type'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
        migrations.CreateModel(
            name='org_role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='lookup.role')),
            ],
        ),
    ]
