# Generated by Django 4.0.4 on 2022-07-18 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_animal_action_type_ownership_change_type_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='market_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Type',
                'verbose_name_plural': 'Market Types',
            },
        ),
    ]
