# Generated by Django 3.2.6 on 2022-06-27 12:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lookup.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        ('lookup', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='establishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('est_size_acres', models.PositiveSmallIntegerField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), lookup.models.max_value_current_year], verbose_name='year')),
                ('gps_lat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('gps_long', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('est_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.est_type')),
                ('org', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation')),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
    ]
