# Generated by Django 3.2.6 on 2022-06-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        ('movement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='animal_type',
        ),
        migrations.AddField(
            model_name='transfer',
            name='animal',
            field=models.ManyToManyField(through='movement.animal_transfer', to='animal.animal'),
        ),
    ]
