# Generated by Django 3.2.6 on 2022-06-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_auto_20220627_2209'),
        ('movement', '0002_auto_20220627_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='vehicle',
            field=models.ManyToManyField(through='movement.vehicle_transfer', to='service_provider.vehicle'),
        ),
    ]
