# Generated by Django 3.2.6 on 2022-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
        ('movement', '0003_transfer_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_notice',
            name='animal_type',
            field=models.ManyToManyField(through='movement.quarantine_animal_type', to='lookup.animal_type'),
        ),
    ]
