# Generated by Django 4.0.4 on 2022-07-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_animal_action_type_ownership_change_type_role_and_more'),
        ('movement', '0006_alter_animal_transfer_action_action_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer_nature',
            new_name='movement_type',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transit_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.transit_category'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='permit_number',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_transfer',
            name='driver_permit_number',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
