# Generated by Django 4.0.4 on 2022-07-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_animal_action_type_ownership_change_type_role_and_more'),
        ('movement', '0007_rename_transfer_nature_transfer_movement_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='animal_transfer_fee',
            new_name='animal_transfer_transaction',
        ),
    ]
