# Generated by Django 3.2.6 on 2022-06-27 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('other_names', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(default='+256', max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nok_name', models.CharField(default='', max_length=100)),
                ('nok_phone', models.CharField(default='+256', max_length=15)),
                ('nok_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=200, null=True)),
                ('identity_doc_number', models.CharField(default='00000000', max_length=50)),
                ('disabled', models.BooleanField(default=False)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_married', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('educ_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.education_level')),
                ('identity_doc_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.identity_doc_type')),
                ('nationality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.nationality')),
                ('nex_of_kin_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.next_of_kin_type')),
                ('sex', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.sex')),
                ('title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.title')),
                ('tribe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.tribe')),
                ('village', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.village')),
            ],
        ),
    ]
