# Generated by Django 4.0.4 on 2022-07-17 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_animal_action_type_ownership_change_type_role_and_more'),
        ('person', '0007_alter_marital_status_log_from_is_married_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='person_role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='person.person')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='lookup.role')),
            ],
        ),
    ]
