# Generated by Django 3.2.6 on 2022-06-27 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('lookup', '0001_initial'),
        ('establishment', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal_number', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='XXX', max_length=30)),
                ('date_of_birth', models.DateField()),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/front')),
                ('side_photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/front')),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.animal_type')),
                ('breed', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.breed')),
                ('dominant_colour', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.dominant_color')),
                ('est', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='establishment.establishment')),
                ('org', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation')),
                ('origin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.origin')),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.person')),
                ('sex', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.sex')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.status')),
            ],
        ),
    ]
