# Generated by Django 4.0.4 on 2022-07-17 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_alter_organisation_org_type_delete_org_type'),
        ('person', '0007_alter_marital_status_log_from_is_married_and_more'),
        ('animal', '0003_alter_animal_dominant_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal_action_logbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='side_photo',
            field=models.ImageField(blank=True, null=True, upload_to='animal_photos/side'),
        ),
        migrations.CreateModel(
            name='change_of_ownership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='animal.animal')),
                ('from_org', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='from_org', to='organisation.organisation')),
                ('from_person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='from_person', to='person.person')),
            ],
        ),
    ]
