# Generated by Django 4.0.4 on 2022-07-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_animal_action_type_ownership_change_type_role_and_more'),
        ('animal', '0004_animal_action_logbook_alter_animal_side_photo_and_more'),
        ('organisation', '0004_alter_organisation_name_alter_organisation_org_type_and_more'),
        ('person', '0008_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_of_ownership',
            name='ownership_change_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='lookup.ownership_change_type'),
        ),
        migrations.AddField(
            model_name='change_of_ownership',
            name='to_org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to_org', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='change_of_ownership',
            name='to_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to_person', to='person.person'),
        ),
        migrations.AddField(
            model_name='animal_action_logbook',
            name='animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='animal.animal'),
        ),
        migrations.AddField(
            model_name='animal_action_logbook',
            name='animal_action_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='lookup.animal_action_type'),
        ),
    ]
