# Generated by Django 4.0.4 on 2022-07-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_remove_establishment_year_establishment_year_est_and_more'),
        ('organisation', '0004_alter_organisation_name_alter_organisation_org_type_and_more'),
        ('lookup', '0009_market_type'),
        ('animal', '0005_change_of_ownership_ownership_change_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.breed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='est',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='establishment.establishment'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.sex'),
        ),
        migrations.AlterField(
            model_name='change_of_ownership',
            name='ownership_change_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lookup.ownership_change_type'),
        ),
    ]
